Make out_identifier id and namespace optional
NestAway/rule-interface pull request #4
Opened 2017-12-12 12:37 UTC by ranveernitk

2017-12-12 12:51 UTC, vishalvijay requested changes
- Specs
- Readme

2017-12-12 12:51 UTC, vishalvijay commented on lib/rule-interface/rule_executor.rb
> +    def execute!(data_hash:, namespace: nil, container:, package:, sesson: 'sesson')
Move mandatory value to the beginning `container `

2017-12-12 12:51 UTC, vishalvijay commented on lib/rule-interface/converter.rb
> +      Thread.current[:id] = 1
Move `:id` to a constant and rename the value to `:rule_interface_out_identifier_id`

2017-12-12 12:51 UTC, vishalvijay commented on lib/rule-interface/converter.rb
> +      unless out_identifier_id
`if out_identifier_id.blank?`

2017-12-13 09:52 UTC, shivanshgaur submitted a review, later dismissed

2017-12-13 09:52 UTC, shivanshgaur commented on lib/rule-interface/converter.rb
>          data_objects.each do |data_object|
Should we have a check here for the case where user wants to insert single object. Something like following:
`
data_hash: {
    product: {
        id: 12,
        name: 'Blah'
    }
}
`

Here product is just a hash and not array.

I suggest to use
`data_objects = [data_objects] unless data_objects.is_a? Array`

2017-12-20 16:03 UTC, vishalvijay approved these changes

2017-12-20 16:04 UTC, merged